### ISSUE TITLE
type-c连接4k显示器只能2k@60，不能4k@60的问题

### ISSUE THREAD

**Issue by lim342** [myd986/LG-gram-14z990#10]
我按照你的bios设置之后，用type-c连接4k显示器只能最高2k@60，是我设置有问题吗？
DVMT Pre-Allocated [64M] 已设置
需要输出4k@60需要做什么样的设置，或者有什么方法，感谢作者！

**Comment by myd986** [comment]
不知道您是否也是i5-8265u？如果是一样的CPU应该不会出现这样的情况，我是可以正常输出4k@60的。
如果您也是8265u，建议先尝试换一下线材。如果还是不行，可以尝试重新给缓冲帧打补丁，具体可以参考[黑果小兵的教程](https://blog.daliansky.net/Tutorial-Using-Hackintool-to-open-the-correct-pose-of-the-8th-generation-core-display-HDMI-or-DVI-output.html)

**Comment by lim342** [comment]
我也是和你一样的cpu，线材也是没有问题的，我使用windows的时候是可以使用4k@60的

![image](https://user-images.githubusercontent.com/68421127/173331117-3e7f348d-e8a5-4211-95ae-7002ea682d05.png)
![image](https://user-images.githubusercontent.com/68421127/173331451-c67a0cae-1c7d-4078-9448-7d2786d8d98a.png)

DVMT Pre-Allocated [64M] 已设置
但是hackintool显示动态显存是57MB，是需要重新给缓冲帧打补丁吗
谢谢你的回复：）

**Comment by myd986** [comment]
看上去应该是可以的，但我已经很久没有弄黑苹果了，我现在也不太确定。
我建议可以先尝试换一根更好的线，同一根线在Windows下可以，在黑苹果下不可以是很正常的。如果换线还是不行应该是核显驱动的问题了，可以尝试重新打缓冲帧补丁，或是尝试升级显示相关的补丁文件
