### ISSUE TITLE
读卡器可用驱动

### ISSUE THREAD

**Issue by cfqbridge** [myd986/LG-gram-14z990#3]
用他们家的：https://github.com/suzuke/LG-Gram-13z980-Opencore/tree/master/EFI/OC/Kexts
13Z990实装可用。

**Comment by cfqbridge** [comment]
https://github.com/cholonam/Sinetek-rtsx
原作者更新2.4了，不知道能不能用。

**Comment by myd986** [comment]
除夕好，其实当时这个扩展就是我提出的，你看一下id，只是这次我自己配制的时候还没有来得及测试

**Comment by myd986** [comment]
除夕好。
是的，我之前注意到了，且在@capricornlee编辑的clover EFI中就有[讨论](https://github.com/capricornlee/LG-Gram13-Z990/issues/19)，只是这次我自己配置EFI时还没有进行测试。
有时间测试好后会添加进efi的。

**Comment by cfqbridge** [comment]
新年好，之前没注意这个讨论。13Z990实装2.4版是OK的，14推测也是统一的读卡器。
