### ISSUE TITLE
HDMI输出黑屏

### ISSUE THREAD

**Issue by RodneyPerhaps** [myd986/LG-gram-14z990#6]
大佬您好！使用您的EFI完美驱动lg gram 15寸，但是HDMI连接外屏黑屏。

**Comment by myd986** [comment]
你接的显示器分辨率是多少？这个HDMI最高输出2k@60

**Comment by RodneyPerhaps** [comment]
> 你接的显示器分辨率是多少？这个HDMI最高输出2k@60

感谢大佬这么快回复，这几天在折腾我的台式机，把这事忘了。。
我的外接显示器是benq bl2480t， 1080p。在切换显示分辨率（从1080p->1080i->720）时，有几秒正常显示，但很快就黑屏，用同学的联想屏（1080p）也尝试了一下，发现根本无法亮屏。。我也尝试用hackintool查看，发现接口识别正常是HDMI。
还请大佬指教，是否是nvram相关的问题？

**Comment by myd986** [comment]
有按照我在介绍里写的那样修改bios和efi文件吗？在我制作这个引导文件时在4k@60的屏上可以最高输出2k@60，在1080p屏上可以输出1080p@60，但我最近没有测试条件。

**Comment by cfqbridge** [comment]
黑屏应该不会吧，我觉得第一步换线，不行重置NVRAM；如果还无效就改一下缓冲帧补丁，enable-hdmi-dividers-fix=1之类。还不行就打一下EDID补丁，说不定是老显示器被当成电视了。

**Comment by cfqbridge** [comment]
> 有按照我在介绍里写的那样修改bios和efi文件吗？在我制作这个引导文件时在4k@60的屏上可以最高输出2k@60，在1080p屏上可以输出1080p@60，但我最近没有测试条件。

我这里倒是可以4K@30，HiDPI正常，我把缓冲帧补丁里的stolenbuffer项删了。Clover时代是可以4K@60的，但是OC一直没试出来。

**Comment by myd986** [comment]
> > 有按照我在介绍里写的那样修改bios和efi文件吗？在我制作这个引导文件时在4k@60的屏上可以最高输出2k@60，在1080p屏上可以输出1080p@60，但我最近没有测试条件。
> 
> 我这里倒是可以4K@30，HiDPI正常，我把缓冲帧补丁里的stolenbuffer项删了。Clover时代是可以4K@60的，但是OC一直没试出来。

我说错了，这个HDMI1.4最高输出4k@30，我确实也曾实现在macOS上输出4k@30。但当我连接4k显示器时，笔记本总是尝试输出4k@60，从而导致黑屏，必须手动调成4k@30，于是我就删除了缓冲帧中仿冒HDMI2.0的内容，现在连接4k显示器也是直接输出2k@60。

**Comment by RodneyPerhaps** [comment]
谢谢大佬们答疑解惑！618买了一条typec扩展坞和一条新HDMI线，最后type-c扩展坞有用，HDMI线还是不能连。😂总之算是可以连接副屏了，虽然有时候会有闪烁的问题。。
这个issue应该可以关掉了。谢谢各位大佬！！
