### ISSUE TITLE
Z990 在BIOS 中怎么设置为第一启动项，看了好多版本的教程，LG没有找到这一项

### ISSUE THREAD

**Issue by fenglookout** [myd986/LG-gram-14z990#7]
在BOOT 下面只能使用“+”使它排在第一位，后续如何操作呢

**Comment by myd986** [comment]
与大多BIOS一样，把需要的条目使用“+”放到第一位就可以了。我想我可能是没有理解你说的话，可以上个图说明一下。

**Comment by fenglookout** [comment]
![IMG_4005](https://user-images.githubusercontent.com/29308550/130983713-352cfd6d-b495-4e69-9a79-0a36271c33c5.PNG)
你好，想问下OC6.6是支持Big_Sur 11.哪个版本，是否是都支持 。
我看别人的教程，设置BIOS后都有设置UEFI硬盘启动优先权，可是LG 15Z990没有找到，导致F10进入选择第一项却没有用，不知道为何。
.Secure BootDisabled → Disabled （安全启动 → 关闭）————这个我也关闭了
       我试过自己安装，也试过聪聪的软件，可是都没有成功，所以我想是不是UEFI这一项错误了

**Comment by myd986** [comment]
OC6.6是支持当前最新版本的。
bios启动项先不用着急，你是否能使用u盘引导启动？还有你是只安装了苹果系统，还是单硬盘双系统，或双硬盘双系统？
单硬盘双系统会复杂一些。
教程可以参考[这里](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html#downloading-macos)

**Comment by fenglookout** [comment]
你好，我是双硬盘双系统。不知为何，使用Clover能够直接进入安装界面，可以选择Windows/MacOS。但是OC不可以，不知道哪里错误了。U盘我也试过了，也不可以，2.0与3.0接口都试过了。按F10进入选择“1”选项没有反应，只有选择win才可以进入系统。
     Clover目前最高支持哪个版本呢？

**Comment by myd986** [comment]
clover已经很久不用了，没测试过。
使用u盘都无法引导，说明你的BIOS或efi有问题。BIOS和efi是否有按照我说的修改？
除了我在readme中明确写出的条目，你还需要关闭安全启动（似乎不是必要）和(f)tmp功能（必要）。
向efi中填入合适的三码（建议在调试时enable **ShowPicker**），将efi放入u盘的ESP分区，然后在BIOS中disable除u盘外所有的启动项，测试能否正常引导。
此外，我不清楚15寸版本是否与14寸版本具有相同的usb map，似乎必须有正确的usb map才可以引导11.3及以上的系统。
