### ISSUE TITLE
您好，我是lg gram 17 z990，但是我的睡眠有问题。

### ISSUE THREAD

**Issue by bze9399** [myd986/LG-gram-14z990#8]
用了你的efi很完美，只是有时候睡眠会睡死（偶尔发生，需要重启。）
我看了你说要重新定制usb，但是我按照网上教程去定制，把kext导入，就驱动不了，进不去系统。
能不能请教你，怎么定制usb。
还有我按照您说的，在bios里面修改，但是bios有时会重制，我不知道是不是我电脑的问题。
现在目前就是睡眠不正常，有没有什么解决办法。
或者你有什么联系方式吗，请教教我。
我的邮箱是405065882@qq.com
我在网上实在找不到办法了，不好意思打扰您。

**Comment by myd986** [comment]
睡眠睡死主要考虑USB map的问题，方法可以参考[这里](https://github.com/corpnewt/USBMap)。
BIOS重置是因为电脑未正常关机，比如强制关机，没有解决办法，正常关机、睡眠不会出现这种情况。

**Comment by bze9399** [comment]
usbmap定制出来的两个文件都放在Kexts里面。
需要在config把里面USB-LG-Gram-14z990文件关掉吗？还是都勾上？
ACPI里面的文件应该不需要动吧。

**Comment by myd986** [comment]
参考[这里](https://post.m.smzdm.com/p/ad223e0z/)

**Comment by bze9399** [comment]
![IMG_20210908_170002](https://user-images.githubusercontent.com/70310246/132479814-ba8ef2b1-f306-4970-b3d9-efb4b1bbaed3.jpg)

**Comment by bze9399** [comment]
还是不行，好郁闷啊

**Comment by myd986** [comment]
我看了你的截图，还是考虑usb定制的问题，猜测是usb定制错误导致雷电三的错误。可恕我学业繁忙，实在没办法给你一些具体的针对性的帮助。

**Comment by bze9399** [comment]
bios里面有没有屏蔽雷电3的选项呀
